### ISSUE TITLE
ACL role permission issue

### ISSUE THREAD

**Issue by Bansiravaliya7** [stape-io/gtm-server-side-magento-module#17]
**Environment**
Module Version: 1.0.15
Magento Version: 2.4.6-p2.

**Issue Description**
We can’t able to give permission to access module configuration settings for other roles

**Screenshots**
Here, you can see in screenshot 1 that the administrator has access to Stape module configuration settings.
![stape](https://github.com/stape-io/gtm-server-side-magento-module/assets/124759214/4c4a55ab-4815-4f79-b2bf-3c538d8d21a3)

Here, you can see in screenshot 2 that, there is no resource available to give permission for this module configuration settings.
![acll](https://github.com/stape-io/gtm-server-side-magento-module/assets/124759214/a918d558-f6cb-441d-80ef-afbaf0595a50)

**Steps to Reproduce(In Default Magento)**
1. Get the Magento clean shop
2. Install the Stape_Gtm module 1.0.15.
3. Go to the “Admin->System->User Roles” and Add New Role.
4. Go to Admin->System->User Roles->Role resources
5. Observe.

**Expected Behavior**
Administrator should give permission to module configuration for other roles and module configuration should be visible for another role user as well.

**Actual Behavior**
Not available resources for module configuration on role resource. And not visible module configuration settings in other roles except which user has all permission.

**Additional information**
**Reason**
In this module, there is no implemented ACL(Access Control List) for module configuration, that's why it is not showing in the role resource and the administrator can’t able to give permission to other roles. So, we need to create an ACL file for this module(i.e etc/acl.xml ).

**Comment by Bukashk0zzz** [comment]
Thanks. 
fixed in https://github.com/stape-io/gtm-server-side-magento-module/pull/18
