### ISSUE TITLE
Product listing sorting not working when module is active

### ISSUE THREAD

**Issue by michel334** [stape-io/gtm-server-side-magento-module#20]
The product listing sorting is not working when module stape/gtm-server-side-magento-module is active

stape/gtm-server-side-magento-module: version 1.0.16
Magento: 2.4.4-p9
Elasticsearch 7

stape plugin file which seems to create the problem
\vendor\stape\gtm-server-side-magento-module\ViewModel\Category.php

public function prepareItems()

This call:

$collection = $productList->getLoadedProductCollection();

Messes up the sorting of the product categorie pages

Some relevant GitHub issues
https://github.com/magento/magento2/issues/4132
Search for: ARGH! Kill me please...

![sorteren](https://github.com/user-attachments/assets/ce13c9db-b131-4de9-9670-990756b2cdd7)

**Comment by Bukashk0zzz** [comment]
Hi,

Thanks for reporting we will take a look.

**Comment by chaikovskyia** [comment]
Hi @michel334 ,
thank you for the report. Could you, please, clarify if that happens on clean Magento or you use some specific theme as I cannot reproduce it on clean Magento installation. We did have such an issue on earlier version of the module, however, we now create new instance of \Magento\Catalog\Block\Product\ListProduct in our module so it is not supposed to overlap with the instance used on the category page.

**Comment by michel334** [comment]
Hi chaikovskyia,
Thanks for checking. I have all themes disabled and the sorting problem persists. When i disable the stape module in Magento backend the sorting works as expected. I attached some more screenshots. The sorting is on the position field of the products attached to a categorie:

![sorting](https://github.com/user-attachments/assets/40650d31-4fc7-456e-8159-4f704c893397)

On the frontend when i click on the up/down arrow of sorting position, nothing happens with stape.io module enabled. When i disable the module the sorting works as expected. We have the latest version of the module (1.0.16)

![sorting-frontend](https://github.com/user-attachments/assets/51058ea2-9e8e-4d56-aa68-214584a88ec9)

I hope this clariefies the issue a bit.
Kind regards,
Michel

**Comment by chaikovskyia** [comment]
@michel334 , I still cannot reproduce the bug on clean Magento 2. I see you use other third party modules, maybe some of the modules impacts the sorting behavior as well.

**Comment by michel334** [comment]
Hi chaikovskyia
You are correct, there was another module that calls:
public function afterGetLoadedProductCollection(\Magento\Catalog\Block\Product\ListProduct $subject, $resultCollection)

I added this code to that module, the same code that is in vendor\stape\gtm-server-side-magento-module\ViewModel\Category.php

        /** @var \Magento\Catalog\Block\Product\ListProduct $productList */
        $productList = $this->layout->createBlock(\Magento\Catalog\Block\Product\ListProduct::class);
        $productList->getToolbarBlock()->setCollection($resultCollection);

The sorting is working correctly now thanks for your assistance.

**Comment by chaikovskyia** [comment]
You're always welcome ;)
